# Generated by Django 2.2.7 on 2019-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32, verbose_name='业务线名称')),
                ('product_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y%m%d', verbose_name='图片')),
                ('product_describe', models.CharField(max_length=255, verbose_name='业务线描述')),
                ('product_manager', models.CharField(max_length=15, verbose_name='业务线负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '业务线管理',
                'verbose_name_plural': '业务线管理',
                'db_table': 'product_info',
            },
        ),
    ]
