# Generated by Django 2.2.7 on 2019-11-26 19:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': '业务线', 'verbose_name_plural': '业务线'},
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='业务线详情'),
        ),
    ]
